### ISSUE TITLE
Is this really working on PHP 5.3.7?

### ISSUE THREAD

**Issue by richbrat** [jeremykendall/password-validator#10]
I noticed `password_hash` needs PHP 5.5 but the README says it's ok with 5.3.7, so if I'm on 5.3.7 is this really going to work (well)?

**Comment by jeremykendall** [comment]
Great question. `password_hash` (and related functions) indeed require PHP 5.5+. There is a userland implementation, however, named [password-compat](https://github.com/ircmaxell/password_compat), which provides the `password_*` functionality for PHP >= 5.3.7. password-compat is added as a dependency in password-validator's [`composer.json`](https://github.com/jeremykendall/password-validator/blob/develop/composer.json#L31), therefore this library will indeed work on PHP 5.3.7+, and it works as well as the PHP 5.5 implementation.

**Comment by richbrat** [comment]
:+1:
