### ISSUE TITLE
Upgrade Decorator should not have user defined salt or cost

### ISSUE THREAD

**Issue by th3fallen** [jeremykendall/password-validator#13]
https://github.com/jeremykendall/password-validator/blob/develop/src/JeremyKendall/Password/Decorator/UpgradeDecorator.php#L53

Has a hardcoded salt and cost.

Please see http://php.net/manual/en/function.password-hash.php for information about why both should be removed or updated to allow the user to define them if they have need.

**Comment by jeremykendall** [comment]
Those hardcoded values are actually there intentionally. `UpgradeDecorator` will validate a user password using a callback (to allow for legacy validation) and then create a new hash of the current password using `password_hash` and those hardcoded values.

The new hash is then passed along to the `PasswordValidator` where it's checked with `password_needs_rehash`. As long as your cost and salt aren't set to 4 and `CostAndSaltForceRehash`, your password is upgraded and the validator returns `Result::SUCCESS_PASSWORD_REHASHED`.

I should probably add a comment in the code. That definitely looks like a bug and I don't mention it anywhere in the docs. Sorry for the confusion!
