### ISSUE TITLE
Add example of using StorageDecorator with UpgradeDecorator to README

### ISSUE THREAD

**Issue by jeremykendall** [jeremykendall/password-validator#14]
@garethellis36 [pointed out](http://jeremykendall.net/2014/01/04/php-password-hashing-a-dead-simple-implementation/#comment-2444350716) an example of using those decorators together is missing from the docs. Gotta add it in.

If anyone is dropping by, you can check out [these examples](tests/JeremyKendall/Password/Tests/Decorator/IntegrationTest.php) from from the test suite.

**Comment by jeremykendall** [comment]
Also clarify how the [Decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) allows stacking of the provided decorators.

**Comment by garethellis36** [comment]
:+1:

**Comment by garethellis36** [comment]
Happy to submit a PR if you like.

**Comment by jeremykendall** [comment]
@garethellis36 That would be awesome!
